### ISSUE TITLE
Endianness discrepancy for KeccakSponge and Memory CTL checks

### ISSUE THREAD

**Issue by LindaGuiga** [mir-protocol/plonky2#1004]
When trying to fix the Memory CTL checks, we noticed that currently, there is a discrepancy between the way the output of keccak is stored in the KeccakSponge Stark and in Memory Stark. Indeed, the memory currently stores the hashes in Little Endian, whereas KeccakSponge stores them in Big Endian, which results in a failed CTL check. 
This is related to commit 0529fa0, where, in `generate_keccak_general`, KeccakSponge CTL checks were solved by changing the way Cpu row values were written so that they matched KeccakSponge rows, but Memory row values were kept unchanged:
```
    let val_u64s: [u64; 4] =
        core::array::from_fn(|i| u64::from_le_bytes(core::array::from_fn(|j| hash.0[i * 8 + j])));
    let hash_int = U256(val_u64s);

    let mut log_push = stack_push_log_and_fill(state, &mut row, hash_int)?;
    log_push.value = hash.into_uint();
```
The first obvious solution would be to change the endianness in Memory (since it is already changed in Cpu). However, this would result in a failed assertion later on. More specifically:
- The state tries are indexed by a hash of the account address, based on the hash that is read in memory. The key is therefore the hash in Little Endian form.
- When accessing the account, the hash of the account address is computed using the ASM version of Keccak, where the result is in the Big Endian form.
- Searching for the account in the state tries therefore results in an assertion error.

To fix the problem without changing the way Keccak outputs are computed, we thought about adding columns in KeccakSponge to store the bytes of the 8 first outputs (4 bytes per u32 limb, or 32 columns in total). This way, we can compare the values in KeccakSponge, Cpu and Memory thanks to the byte values. Do you have a better solution in mind?

**Comment by Nashtare** [comment]
I guess this can be closed now.

**Comment by LindaGuiga** [comment]
Memory CTL and endianness are handled in [this PR](https://github.com/mir-protocol/plonky2/pull/1026)
