### ISSUE TITLE
Bootloading code and contract

### ISSUE THREAD

**Issue by LindaGuiga** [mir-protocol/plonky2#1070]
For bootload_contract and bootload_code, where is the code/contract supposed to be loaded from, and how are these labels different from extcodecopy? 
Since the code is supposed to be provided by the prover, I would assume we need to use a function in PROVER_INPUT, but I was then wondering what the address in the initial stack corresponds to: is it the destination address?

**Comment by dlubarov** [comment]
Yeah seems like it's sort of been replaced by `load_code`, so feel free to delete that file.

Somewhat related though, I think we want a wrapper around `load_code` that calls `jumpdest_analysis`, when we're loading code that we're going to execute (for message processing or contract creation, but not `CODECOPY` etc).

**Comment by wborgeaud** [comment]
We currently perform the jumpdest analysis in `%enter_new_ctx` which should be called every time new code is executed.

**Comment by dlubarov** [comment]
Oh I see, sounds good then!

**Comment by wborgeaud** [comment]
`bootloader.asm` has been deleted in #1072.
