### ISSUE TITLE
Quotient = -1 causes range check to fail in ArithmeticStark

### ISSUE THREAD

**Issue by LindaGuiga** [mir-protocol/plonky2#1127]
@unzvfu We noticed that proof verification of `CreatePrecompiles_{6, 7}` fails. This is because, in some cases when computing `SubFp254`, the computed quotient was equal to -1, but the quotient columns are range checked between 0 and 2^16 in `ArithmeticStark`. Since `MODULAR_QUO_INPUT` columns overlap with some `AUX_INPUT_REGISTER` columns, we can't just remove `MODULAR_QUO_INPUT` columns from the range check. Changing modular computations would also affect `divmod` (and, seemingly, other parts of the code as well).

Do you have an idea of how to solve this issue?

**Comment by unzvfu** [comment]
Thanks for reporting this issue @LindaGuiga.

Could you please post a link to those failing tests (or a gist, or just copy the json here)? I can't seem to find them in [`ethereum/tests`](https://github.com/ethereum/tests).

**Comment by Nashtare** [comment]
Hi @unzvfu! Linda is referring to this test: https://github.com/ethereum/tests/blob/0902578614503cb52e9b115f8714a17c39787c58/GeneralStateTests/stCreate2/create2callPrecompiles.json, where 6 and 7 refer to the variant cases within the test (last two transactions).

**Comment by unzvfu** [comment]
Ok, just had a closer look at this and found the source of, and solution to, the problem. I should have a PR done in the next few days.
