### ISSUE TITLE
About constraints related to `reg_preimage` 

### ISSUE THREAD

**Issue by qope** [mir-protocol/plonky2#1133]
Regarding the evm/keccak implementation, it appears that the constraints related to `reg_preimage` are only the following one.

https://github.com/mir-protocol/plonky2/blob/00579850be0fc9caeae31ec21815b923d985187c/evm/src/keccak/keccak_stark.rs#L267-L273

This means that `reg_preimage` can be chosen independently of `reg_a` and others.

I think this would cause a soundness issue when `reg_preimage` is subject to cross-table lookups.

Am I overlooking something? I appreciate your feedback. Thank you.

**Comment by shuklaayush** [comment]
Shouldn't this also be constraining the higher bits?

**Comment by dlubarov** [comment]
Thanks for reporting, @npwardberkeley could you take a look later?

**Comment by shuklaayush** [comment]
I'd like to create a PR for this if that's fine

**Comment by npwardberkeley** [comment]
Oh yes, go for it!

**Comment by shuklaayush** [comment]
I created a PR to constrain the higher bits of the `preimage`. Should I also add a constraint that `reg_a` and `reg_preimage` should be the same at the start of each input?

**Comment by Nashtare** [comment]
Closing as #1201 and #1202 have been merged.
