### ISSUE TITLE
Decoding issue when combining opcode flags in CpuStark

### ISSUE THREAD

**Issue by LindaGuiga** [mir-protocol/plonky2#1141]
We are currently trying to combine flags, as indicated in the TODOs in cpu/columns/ops.rs. But the decoding in decode.rs requires aligned, contiguous opcode blocks of length a power of 2, as it makes decoding easier. We were wondering wether we could change various opcode values (for example, set `MLOAD_GENERAL = 0xf8` and `MSTORE_GENERAL = 0xf9` so that the combined flag `m_op_general` can have start index 0xf8) to abide by those requirements. 

A more complex case is the TODO to combine ADD, MUL, SUB, DIV, MOD, ADDFP254, MULFP254, SUBFP254, LT, and GT into one flag, since their opcodes are not contiguous and some operations are kernel_only. This would imply changing multiple opcodes in the whole list of `OPCODES`.

Did you have anything else in mind for those combinations, besides modifying the opcodes?

**Comment by hratoanina** [comment]
There's another issue with combining flags:
Stack behavior and gas costs for simple opcodes can only be specified at the OP flag level, but individual operations under a combined flag may have different stack behaviors or gas costs. For stack behavior it's possible to set it to `None` and then handle the different operations manually, and something similar should be possible for the gas, but this would be ugly with many combined flags and run against the very point of the generic handling of `stacks.rs` and `gas.rs`.

Would it be possible to bind stack behaviors and gas costs to individual operations via not only OP flags but opcode bits as well instead?

**Comment by Nashtare** [comment]
Handled manually for combined flags that are not consecutive.
