### ISSUE TITLE
Proof verification failure on `stZeroKnowledge2/ecmul_1-2_0_28000_80`

### ISSUE THREAD

**Issue by Aphoh** [mir-protocol/plonky2#1142]
Repro is simple: run `evm_test_runner` pointing to the latest version of plonky2. Logs look like
```bash
│                          name                           │               status                │
├─────────────────────────────────────────────────────────┼─────────────────────────────────────┤
│GeneralStateTests/stZeroKnowledge2/ecmul_1-2_0_28000_80_0│Evm error: Proof verification failed.│
│GeneralStateTests/stZeroKnowledge2/ecmul_1-2_0_28000_80_1│Evm error: Proof verification failed.│
│GeneralStateTests/stZeroKnowledge2/ecmul_1-2_0_28000_80_2│Evm error: Proof verification failed.│
│GeneralStateTests/stZeroKnowledge2/ecmul_1-2_0_28000_80_3│Evm error: Proof verification failed.│                                           
```

This comes from `plonky2_evm::verifier::verify_proof` returning `Err(())`.

Also worth mentioning that theses verification errors happen for several other test cases in the `stZeroKnowledge` suite, this is just a nice short one with 4 transactions.

**Comment by Nashtare** [comment]
It seems it's been addressed by a PR already merged: https://github.com/mir-protocol/plonky2/pull/1140.

**Comment by pgebheim** [comment]
@Aphoh can you confirm these tests pass with this patch applied and then close?

**Comment by Aphoh** [comment]
They pass!
