### ISSUE TITLE
Implement BLOCKHASH opcode

### ISSUE THREAD

**Issue by wborgeaud** [mir-protocol/plonky2#1173]
The BLOCKHASH opcode returns the hash of one of the 256 most recent complete blocks (not including the current one).

Here are some ideas on how to implement it:

- Output a value provided by the prover using `PROVER_INPUT`. (Not very sound)
- Add the last 256 block hashes to the public values and check for consistency in the block aggregation proof.
- Write the block hashes somewhere in the state trie (or the txs/receipts tries), preferably at a slot that cannot otherwise be accessed (e.g. the all zeros slot). This would slightly impair Ethereum equivalence. (Can be used to query older blocks if needed)
- Use an extra vector commitment (e.g. Merkle tree) that is updated at every block. (Can be used to query older blocks if needed)

**Comment by Nashtare** [comment]
I'd prefer going for options 2 or 4, as 1 is not really satisfactory as you pointed out, and 3 doesn't look super neat in terms of type-1 Ethereum equivalence. In addition, following that last point, I wonder if the extra feature provided by 3 and 4 of being able to query older blocks is really necessary, given that Ethereum contracts cannot.

**Comment by wborgeaud** [comment]
> In addition, following that last point, I wonder if the extra feature provided by 3 and 4 of being able to query older blocks is really necessary, given that Ethereum contracts cannot.

Yeah I mentioned that because Polygon zkEVM supports it. Also it could be useful later on for applications like proof of historical state.
But I agree we shouldn't implement it at first to maintain strict Ethereum equivalence.
