### ISSUE TITLE
Implement Serde Serializer and Deserializer for Targets

### ISSUE THREAD

**Issue by Dimo99** [mir-protocol/plonky2#1197]
It seems that the Targets serialization doesn't currently implement the Serde interfaces. Implementing these interfaces would greatly simplify the process of serializing and deserializing structs containing targets. This would reduce the need to rewrite similar boilerplate code across various structs. Are there any specific reasons for this omission, or is it something that could be considered for future updates?

**Comment by dlubarov** [comment]
I think it's probably fine to add, we just hadn't come across a use case where we needed to serialize targets. Could you explain a bit where it comes up?

**Comment by Dimo99** [comment]
I am serializing/deserializing circuits and to be able to assign the targets with values I also need to serialize and deserialize some targets which I have grouped into structs

**Comment by Dimo99** [comment]
I am even wondering about some generic way of assigning the values cause currently I have structures like this

```
pub struct ValidatorPoseidonTargets {
    pub pubkey: [Target; 7],
    pub withdrawal_credentials: [Target; 5],
    pub effective_balance: [Target; 2],
    pub slashed: [Target; 1],
    pub activation_eligibility_epoch: [Target; 2],
    pub activation_epoch: [Target; 2],
    pub exit_epoch: [Target; 2],
    pub withdrawable_epoch: [Target; 2],
}
```
```
#[derive(Serialize, Deserialize, Debug, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct ValidatorPoseidonInput {
    #[serde(serialize_with = "to_string", deserialize_with = "from_str")]
    pub pubkey: Vec<u64>,
    #[serde(serialize_with = "to_string", deserialize_with = "from_str")]
    pub withdrawal_credentials: Vec<u64>,
    #[serde(serialize_with = "to_string", deserialize_with = "from_str")]
    pub effective_balance: Vec<u64>,
    #[serde(serialize_with = "to_string", deserialize_with = "from_str")]
    pub slashed: Vec<u64>,
    #[serde(serialize_with = "to_string", deserialize_with = "from_str")]
    pub activation_eligibility_epoch: Vec<u64>,
    #[serde(serialize_with = "to_string", deserialize_with = "from_str")]
    pub activation_epoch: Vec<u64>,
    #[serde(serialize_with = "to_string", deserialize_with = "from_str")]
    pub exit_epoch: Vec<u64>,
    #[serde(serialize_with = "to_string", deserialize_with = "from_str")]
    pub withdrawable_epoch: Vec<u64>,
}
```
And I have defined a trait 
```
pub trait SetPWValues<T> {
    fn set_pw_values(&self, pw: &mut PartialWitness<GoldilocksField>, source: &T);
}
```

And I implement it like this

```
fn set_pw_values(
    pw: &mut PartialWitness<GoldilocksField>,
    target: &[Target],
    source: Vec<u64>,
) {
    for i in 0..target.len() {
        pw.set_target(target[i], GoldilocksField::from_canonical_u64(source[i]));
    }
}

impl SetPWValues<ValidatorPoseidonInput> for ValidatorPoseidonTargets {
    fn set_pw_values(&self, pw: &mut PartialWitness<GoldilocksField>, source: &ValidatorPoseidonInput) {
        set_pw_values(pw, &self.pubkey, source.pubkey.clone());

        set_pw_values(
            pw,
            &self.withdrawal_credentials,
            source.withdrawal_credentials.clone(),
        );

        set_pw_values(
            pw,
            &self.effective_balance,
            source.effective_balance.clone(),
        );

        set_pw_values(pw, &self.slashed, source.slashed.clone());

        set_pw_values(
            pw,
            &self.activation_eligibility_epoch,
            source.activation_eligibility_epoch.clone(),
        );

        set_pw_values(
            pw,
            &self.activation_epoch,
            source.activation_epoch.clone(),
        );

        set_pw_values(pw, &self.exit_epoch, source.exit_epoch.clone());

        set_pw_values(
            pw,
            &self.withdrawable_epoch,
            source.withdrawable_epoch.clone(),
        );
    }
}
```

And I am assigning the targets in the following way
```
for i in 0..validator_balance_input.validators.len() {
        targets.validators[i].set_pw_values(&mut pw, &validator_balance_input.validators[i]);
}
```

But I have the feeling this is very generic code and it can be implemented automatically with some macro for any kind of structure.

**Comment by Nashtare** [comment]
Addressed by https://github.com/mir-protocol/plonky2/pull/1214.

**Comment by puma314** [comment]
hey @Dimo99, we've also encountered a lot of times that we have to have code like this, where we find ourselves repeating the exact same logic for serializing/deserializing structs of Targets and having to set/get them from witnesses. We've been working on a layer on top of `plonky2` that we call `plonky2x` that introduces nice abstractions for these cases. 

In particular, we introduce a trait `CircuitVariable` that you can see [here](https://github.com/succinctlabs/succinctx/blob/main/plonky2x/src/frontend/vars/mod.rs#L27) that wraps structs of targets and lets us easily have the code to get/set values within a witness.

It's a much cleaner abstraction and we've been able to go a lot faster with writing circuits with `CircuitVariable` (you can also automatically derive it on structs that are composed of `CircuitVariable` as well).

If you'd be interested in using it, feel free to DM me on Telegram (it's pumathe<my_first_name> where <my_first_name> is puma with the beginning letter removed).
