### ISSUE TITLE
Plonky2 is Snark or Stark?

### ISSUE THREAD

**Issue by mostafamshk** [mir-protocol/plonky2#1210]
Hey guys, 
I studying on zkp algorithms and if I get it right, Plonky2 is a recursive SNARK.
In fact, [this link](https://polygon.technology/blog/introducing-plonky2) has a quote that says:
```
Plonky2 is a recursive SNARK that is 100x faster than existing alternatives and natively compatible with Ethereum. It combines PLONK and FRI for the best of STARKs, with fast proofs and no trusted setup, and the best of SNARKs, with support for recursion and low verification cost on Ethereum.
```
What I get from this quote is that Plonky2 actually uses some features of Stark and this is where I get a little confused. I wanted to know if there is a Stark implementation for Plonky2 that can tested or if this repository is the only implementation of Plonky2 that is actually Snark and there is no Stark implementation at all. 

I appreciate it if you guys could help me understand this.

**Comment by npwardberkeley** [comment]
Hi!

Just a note, STARKs and SNARKs are not separate categories. Assuming we're only talking about non-interactive protocols, all STARKs are SNARKs; in particular, STARKs are the SNARKs that are transparent (requiring no trusted setup).

Often, STARK is used as shorthand for _AIR-based and FRI-based STARK_, which is one particular (and quite popular) type of SNARK. Most modern SNARKs are built from an IOP (interactive oracle proof) and a PCS (polynomial commitment scheme). In the case of these common STARKs, AIR is the choice of IOP and FRI is the choice of PCS.

The blurb you're quoting is simply referring to the fact that Plonky2 uses FRI as its PCS, similar to these STARKs, but uses an IOP similar to the one from Plonk (which is a SNARK but not a STARK).

However, this repo also includes `starky`, which is built from AIR + FRI, like a classic STARK.

Hope that helps!

**Comment by mostafamshk** [comment]
Hey, 
that was a nice, short and also complete explanation. 
Thanks.
