### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by skardas** [mir-protocol/plonky2#426]
On Mac with rustc 1.58.0-nightly (65f3f8b22 2021-11-21)

RUST_LOG=debug RUSTFLAGS=-Ctarget-cpu=native cargo test --release test_recursive_recursive_verifier -- --ignored

The test did not worked.

[https://www.dropbox.com/s/xipw15lmi76uxvb/Screen%20Shot%202022-01-11%20at%2013.01.47.png?dl=0](https://www.dropbox.com/s/xipw15lmi76uxvb/Screen%20Shot%202022-01-11%20at%2013.01.47.png?dl=0)

**Comment by bpfarmer** [comment]
Hi @skardas - could you try updating to 1.59.0-nightly? Thanks.

**Comment by skardas** [comment]
Thx, it works now.
