### ISSUE TITLE
Need public API for creating proof targets and populating them using proof objects

### ISSUE THREAD

**Issue by dlubarov** [mir-protocol/plonky2#431]
As @Sladuca pointed out,

> How do I construct recursive circuit outside the `plonky2` crate? I see in the test suite for `recursive_verifier.rs` that `recursive_proof` uses  `proof_to_proof_target` and `set_proof_target`, which turns a proof into a target and adds the proof as an input in a `PartialWitness`. Is there a reason these two functions are only in the test suite? 
>
> `proof_to_proof_target` seems to me like it would fit as a  `CircuitBuilder` method (it takes a `&mut CircuitBuilder`) and `set_proof_target` seems similar to other `PartialWitness` methods.
>
> Also, does one need to build a new recursive circuit for each proof, or is it possible to build one recursive 'outer' circuit and feed it different proofs for the same 'inner' circuit as input? 

I'm not sure about the `proof_to_proof_target` API though; let's think about some alternatives.

**Comment by Sladuca** [comment]
I think the lazy `add_recursive_verifier` with the `VerifierCircuitTarget` fields passed as public inputs method discussed in discord makes sense, with one caveat - how would the user get the target needed to set the proof input with something like `pw.set_verifier_target(target, value)`?

**Comment by dlubarov** [comment]
@Sladuca I think this may have been discussed in Discord? Let me know if not. I also just created #446 about "unbounded" recursion; let's use this one just for basic bounded recursion.

I made #445 which mostly addesses this, adding a public `add_virtual_proof_with_pis` method to replace `proof_to_proof_target`. After that we just need to make `set_proof_target` public.

**Comment by Sladuca** [comment]
@dlubarov Yes it was. Thanks, I'll check this out and reach out on discord with any questions/comments/concerns.
