### ISSUE TITLE
GMiMC, Rescue aren't compatible with `GoldilocksField`

### ISSUE THREAD

**Issue by dlubarov** [mir-protocol/plonky2#432]
Our GMiMC and Rescue code is using `x^3`, since when we wrote it we were using `p = 2^64 - 9 * 2^28 + 1`, but we're now using `p = 2^64 - 2^32 + 1`.

We could update it to `x^7` (at least Rescue; GMiMC specifies `x^3` though others might be okay). That said, maybe we should just delete them, since we have no plans to use GMiMC or Rescue.

Thanks to Vijay who noticed this incompatibility.

**Comment by unzvfu** [comment]
Good catch!

The only argument I can see for keeping either is to compare throughput with our Poseidon implementation, but I don't see much value in that anymore now that we've decided on Poseidon. So I'd vote to remove GMiMC and Rescue.
