### ISSUE TITLE
Work around possible division by zero

### ISSUE THREAD

**Issue by dlubarov** [mir-protocol/plonky2#456]
Our permutation argument has the possibility of division by zero, which leads to a completeness error of `deg / |F|`. Since `|F| ~= 2^64`, this is non-negligible. Chances are we won't actually encounter this, unless we're generating millions of large proofs per second, but we should probably plan for it to be safe.

We could avoid division entirely by separating `Z(x)` into two product accumulators, but that would increase costs. It seems best to work around this by just having the prover retry with different randomness.

Most instances probably have some sort of "free witness space" where a random (or incrementing) value could be inserted, but ideally this should be fully generic. So I think we should have a "free element" in the protocol transcript itself, which the prover would send. They could send it at any point before the verifier samples random beta/gamma, though it might be simplest to do it immediately before, so we're only backtracking a small part of the protocol.

Even if we don't implement the retry logic yet, we should probably have this free element in the transcript, and set it to a random value. Then if this edge case does comes up, we could panic, and (in our rollup setting) restarting the node would "fix" the problem. That might be good enough for now since it is unlikely.

**Comment by wborgeaud** [comment]
I think this should be rare enough that it doesn't warrant the added complexity of adding backtracking. We could have the prover return a special `DivisionByZero` error that could be caught by whoever calls the prover.

To add randomness to the transcript, we could use the `PublicInputGate` present in every circuit. This gate uses only 4 wires, so we could add a 5th one set to a random value.

**Comment by dlubarov** [comment]
Yeah returning an error sounds good, rather than panicking.

Using `PublicInputGate` is a good idea, though its columns might change if we switch to Plonky1-style public inputs? I'll need to give that more thought. An alternative would be to have the builder add a `NoopGate` with a `RandomValueGenerator` to generate one (or all) of its values.

**Comment by wborgeaud** [comment]
Yeah adding a `NoopGate` with random values would work too, but in the case of a circuit with exactly a power of 2 gates we would have to pad to the next power of 2. It shouldn't happen often, but could get annoying when it does.

We could also look for a gate in the circuit with `G::num_wires() < config.num_wires()` and add a random value to this gate. If no such gate exists we could use the `NoopGate + random value` solution.

**Comment by dlubarov** [comment]
I think this is also an issue with our FRI proof-of-work by the way, which has a comparable completeness error.
