### ISSUE TITLE
Issues with small circuits

### ISSUE THREAD

**Issue by wborgeaud** [mir-protocol/plonky2#463]
- `MerkleTree::new` panics when `leaves.len() == 1 << cap_height`. The expected behavior is a Merkle tree with empty digest and with cap set to the hash of the leaves.
- `MerkleTree::new` rightfully panics when `leaves.len() < 1 << cap_height` with a subtraction overflow. We should probably make it panic with a clear error message like `panic!("Cap height should be at most log(leaves.len())")`.  For circuits, we should also probably catch this earlier, e.g., in `CircuitBuilder::build()`.
- In `compute_quotient_polys`, a hardcoded `BATCH_SIZE=32` is used. This leads to a panic if the size of the LDE is less than 32.

**Comment by nbgl** [comment]
Not handling very small circuits in `compute_quotient_polys` was a deliberate choice for simplicity. I’m happy to add the special case if you think it’d be useful.

**Comment by nbgl** [comment]
It’s more to do with how to the gates are vectorized. If the circuit size is not a multiple of the vector length, then you need extra code to deal with the leftovers.

I’ll make a PR for it today.

**Comment by nbgl** [comment]
Fixed in #467 and #469. (I thought extra changes were needed to vectorized gate evaluation code to account for leftovers, but it turns out I've already implemented that.)
