### ISSUE TITLE
Visibility issues

### ISSUE THREAD

**Issue by yindavidyang** [mir-protocol/plonky2#494]
I had difficulties using this library due to visibility issues. For example:

- In the `plonky` crate, the functions `prove` (in prover.rs) and `verify` (verifier.rs) are only visible within the crate. 
- The contents of `CircuitData`, i.e., `prover_only`, `verifier_only` and `common`, are only visible within the crate.
- The structs `ProverOnlyCircuitData`, `VerifierOnlyCircuitData` are only visible within the crate.
- The content of `ECDSAPublicKeyTarget` is private.

Is it possible to make these items publicly visible?

**Comment by yindavidyang** [comment]
Thanks for the prompt reply. Actually the code is very well written and easy to read, so the lack of documentation isn't a big hurdle.

Yes I saw that CircuitData has a publicly a visible `prove` function. The problem with this function is that it passes a hardcoded `TimingTree::default()` to the underlying `prove` function, and I can't find a way to print the results of this default `TimingTree` ...

Regarding `CircuitData::verify`, the problem is that `CircuitData` contains prover-only data, and therefore the verifier isn't supposed to have access to it. It seems that the verifier should use  `VerifierCircuitData` instead. However, I didn't find a way to convert `CircuitData` to `VerifierCircuitData`. While I could get `VerifierCircuitData` through `CircuitBuilder::build_verifier`, doing so is costly since this function (re-)builds the whole circuit. For example, on my laptop, building an ECDSA verification circuit took more than 80 seconds, which is almost as slow as proving the circuit ...

**Comment by npwardberkeley** [comment]
Oh I'm sorry, just saw this — for `ECDSAPublicKeyTarget` pub would totally make sense, I'll change that now

**Comment by yindavidyang** [comment]
Thanks that helps a lot.
