### ISSUE TITLE
Can U32ArithmeticGate use 4 wires instead of 5?

### ISSUE THREAD

**Issue by yindavidyang** [mir-protocol/plonky2#504]
Each `op` of `U32ArithmeticGate` uses 5 wires: 2 multiplicands, an addend, and 2 output wires (lower half and upper half). I wonder if it's ok to use a single output wire that packs both the lower and upper halves? 

In particular, in `U32ArithmeticGate::eval_unfiltered`, after obtaining `combined_low_limbs` and `combined_high_limbs`, can I pack both into an array, and then call `FieldExtension::from_basefield_array` to turn it into an extension field element (to be compared with the output wire in a constraint)?

**Comment by wborgeaud** [comment]
Hey @yindavidyang, having `U32ArithmeticGate` return the two halves of the output is useful in our non-native arithmetic code since the gate takes care of range-checking the two halves to be below 2^32.
If you just want the full output of the arithmetic operation, you can use the `ArithmeticGate` which is similar and uses 4 wires: 2 multiplicands, 1 addend, and 1 output wire.

**Comment by yindavidyang** [comment]
Yes I get it that `U32ArithmeticGate` needs two outputs (for the lower and upper halves), unlike `ArithmeticGate`. My question is whether we can pack these two outputs into a single routed wire.

For example, let's say the lower half is 123, and the upper half is 456 (i.e., the output is 456*2^32+123). Instead of outputting 123 and 456 with two routed wires, I wonder if we can output one wire with 123+456i (where i^2 = 7 in `GoldilocksField`). In the next gate, we can't use this packed output (123+456i) directly. Two unpack it, we can use two additional advice (i.e., not routed) wires x and y, with the constraint that x+yi = 123+456i.

**Comment by wborgeaud** [comment]
Oh I see what you mean now.

> Instead of outputting 123 and 456 with two routed wires, I wonder if we can output one wire with 123+456i.

This isn't possible since wires can only hold base field values, not extension field values. To represent extension field elements we need two wires, see the `ExtensionTarget` type.

**Comment by yindavidyang** [comment]
I see -- thanks for the clarification.

I saw that the members of `EvaluationVars` are extension field elements, so I thought that a wire can hold extension field values. Now that I think about, maybe the reason `EvaluationVars` uses extension values is to satisfy 100-bit security since the field is pretty small ...
