### ISSUE TITLE
Do not set a global allocator

### ISSUE THREAD

**Issue by recmo** [mir-protocol/plonky2#532]
I agree that jemalloc is great and can outperform the default allocator (especially on musl builds). In fact I use mimalloc for these reasons, which is smaller and faster according to the authors.

But it is not appropriate for a library to set the global allocator. The global allocator can only be set once, or else the build will fail. If plonky2 appears as a dependency anywhere in a project that uses a custom allocator, the build will fail. If another library where to do the same, those two could never co-exist, etc.

Downstreams projects may want to use mimalloc instead or may want to wrap it with custom logic to add metrics and logging to allocations.

**Comment by nbgl** [comment]
Yeah, I agree and this was [actually a concern](https://github.com/mir-protocol/plonky2/pull/347#issue-1049119673) when I made the change. At the time Plonky2 wasn’t public so this wasn’t an issue, but it’s probably worth changing now. (However, I’d like to make sure that our benchmarks still use Jemalloc.)
