### ISSUE TITLE
Order matters when evaluating constraints to `RecursiveConstraintConsumer`

### ISSUE THREAD

**Issue by Sladuca** [mir-protocol/plonky2#538]
When implementing `eval_ext_recursively`, it seems that the order in which the constraints added to the `RecursiveConstraintConsumer` matters, specifically that the order matches that in `eval_packed_generic`. One order works just fine, while for the other order it fails saying something like `Partition containing ... was set twice with different values`, even with the same exact constraints.

Is this intended behavior?

**Comment by wborgeaud** [comment]
Yes this is intended. 
The actual constraint that is used to compute the STARK is a linear combination of the constraints given in the `ConstraintConsumer` with powers of some random challenge `alpha`. So constraints `f_0, f_1, ..., f_n` will be combined into `f_0 + alpha * f_1 + ... + alpha^n * f_n`.
So a different constraint order will result in a different linear combination.

**Comment by Sladuca** [comment]
Oh I see! Thank you.
