### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jcarlosi** [mir-protocol/plonky2#542]
Plonky2 is a great lib, and it would be great if it could be released under an open license, hopefully MIT but even copyleft would be appreciated.

Even disregarding the mind-boggling performance and recursive proofs, the core Turbo/UltraPLONK implementation is pretty much the only usable one out there:

- [Aztec/barretenberg](https://github.com/AztecProtocol/barretenberg): huge c++ project, not very modular
- [zcash/halo2](https://github.com/zcash/halo2): extremely complex circuit builder interface, no goldilocks
- [dusk/plonk](https://github.com/dusk-network/plonk): less mature, no hash gadgets, bls12381 only

So licensing plonky2 would help researchers a lot :)

**Comment by themighty1** [comment]
Came here to say the same thing. Heard about plonky2 breakthrough speeds in Jan but waited until the license is decided upon. Decided to re-visit today to benchmark how it performs for my use-case. Alas, lack of an Apache 2.0/MIT license is a non-starter.

**Comment by dlubarov** [comment]
I'm sorry for the delay here, internally we haven't made a final decision on this just yet, but we hope to have an update soon.
