### ISSUE TITLE
Potential Bug: CircuitData is not always built the same for circuits containing Merkle Proofs - breaks usage of merkle proofs within circuits.

### ISSUE THREAD

**Issue by Shalevos** [mir-protocol/plonky2#684]
When trying to prove knowledge of a leaf in a merkle tree using the `builder.verify_merkle_proof` api the builder generates different CircuitData every time.
This is true for both the `CircuitConfig::standard_recursion_zk_config()` and `CircuitConfig::standard_recursion_config()` configs.

This breaks using merkle proofs inside circuits.
Meaning that when sending the proof to a different device, that device won't be able to always verify the proof since it generated different CircuitData.
For circuits without the merkle proofs this doesn't occur - the CircuitData is always generated to be exactly the same.
Also, about 50% of time both the prover and verify will generate the same CircuitData and then the proof verification does indeed pass.

I created a small repo that reproduces this exactly and makes playing around with this bug easy and clear.
https://gitlab.com/Shalevos/merkle-tree-circuit-data-bug
I tried for a few hours to figure this out myself but would love the help of the devs on this.

Thanks,
Shalev

**Comment by dlubarov** [comment]
Thanks for reporting, I'll look into this. Looks like `constants_sigmas_cap` differs, so either our preprocessed polynomials aren't deterministic, or there's a bug in our code that builds a Merkle tree.

**Comment by dlubarov** [comment]
It looks like this bit of code could lead to different wiring based on `HashMap`'s iteration order: https://github.com/mir-protocol/plonky2/blob/ce456fb8ea436687aa70f5029c78dcc3d6f56282/plonky2/src/plonk/circuit_builder.rs#L663
