### ISSUE TITLE
Field64 causing unexpected behaviour on fibonacci example

### ISSUE THREAD

**Issue by LucasRodriguez** [mir-protocol/plonky2#825]
Testing the repo, I found that running the fibonacci example will output weird results as soon as `u64` "overflows". Naturally it doesn't overflow per se in the code, but it will start causing unexpected behaviour when managing the numbers. 

Running the fibonacci sequence only works as expected up until n=93. 

n = 92  result : `7540113804746346429`....| expectation: `7540113804746346429`
n = 92  result : `12200160415121876738`..| expectation: `12200160415121876738`
n = 94  result : `19740274219868223167`..| expectation: `1293530150453638846`

at n = 94; It starts to behave in an unexpected way.

**Comment by unzvfu** [comment]
Hi Lucas. In fact the example actually only treats the Fibonacci elements **modulo p** where _p_ = 2^64 - 2^32 + 1 is our base field prime. If you look at the numbers for n=94, note that `19740274219868223167 - 1293530150453638846 == p`. If you run the code like so:
```
$ cargo run --example fibonacci
100th Fibonacci number mod |F| (starting with 0, 1) is: 3736710860384812976
```
note that the output says it's only true `mod |F|`, and indeed `|F| = p`. The 100th Fibonacci number is `354224848179261915075 == 3736710860384812976 mod p`.

Hope this clarifies.
