### ISSUE TITLE
location of file `poseidon_constants.sage`

### ISSUE THREAD

**Issue by jan-ferdinand** [mir-protocol/plonky2#875]
The comment in [`poseidon_goldilocks.rs`](https://github.com/mir-protocol/plonky2/blob/main/plonky2/src/hash/poseidon_goldilocks.rs) states that round constants and the MDS matrices' components “*must* be generated using the `poseidon_constants.sage` script in the `mir-protocol/hash-constants` repository.”

I seem to be unable to find said script. Could you point me in the right direction?

**Comment by unzvfu** [comment]
You can find it here: https://github.com/mir-protocol/hash-constants/blob/master/poseidon_constants.sage

**Comment by unzvfu** [comment]
@jan-ferdinand Apologies, I just realised that the repository is private, which explains why you can't see it! I'm not sure we want to make the repository public just yet; we'll discuss and get back to you.

**Comment by jan-ferdinand** [comment]
Thanks! In case it helps making a decision: (I think) I only care about that particular script.

**Comment by unzvfu** [comment]
> Thanks! In case it helps making a decision: (I think) I only care about that particular script.

Could you elaborate on what questions you're looking to answer? That script really just takes an MDS matrix as input and generates the constants used in [`poseidon_goldilocks.rs`](https://github.com/mir-protocol/plonky2/blob/main/plonky2/src/hash/poseidon_goldilocks.rs) in a way that is compatible with the assumptions of that code (which basically follows Section B of the [Poseidon paper](https://eprint.iacr.org/2019/458.pdf)); I'm not sure how informative that will be.

**Comment by jan-ferdinand** [comment]
What I want, from zoomed-out to zoomed-in:

1. An apples-to-apples comparison of Poseidon to our new hash function, [Tip5](https://eprint.iacr.org/2023/107).
2. An efficient implementation of Poseidon over $\mathbb{F}_{2^{64} - 2^{32}+1}$, state size 16, 192 bits of security.
3. `MDS_MATRIX_CIRC` and `MDS_MATRIX_DIAG` for above parameters.
4. A way to generate `MDS_MATRIX_{CIRC, DIAG}`.

I was hoping that in using the mentioned script, I could fulfill wish 4. This, in turn, would enable me to fulfill all above wishes. In the end, I only care about wish 1. :blush:

**Comment by unzvfu** [comment]
@jan-ferdinand: I'm happy to announce that the [`hash-constants`](https://github.com/mir-protocol/hash-constants) repository is now public. Feel free to raise any issues you come across there; I'll do my best to address them, but do keep in mind that the original purpose was for internal use only (so it is a bit of a mess, sorry!) and it is not actively developed (so my capacity is a bit limited). Bugs will definitely be addressed though!

Please keep us informed about your benchmarking work, we are very interested in the relative merits of Poseidon vs Tip5!

**Comment by jan-ferdinand** [comment]
Thank you very much! And thanks as well for the recently added documentation on that repo – much appreciated. :bow:

I'll keep you posted about my findings. :slightly_smiling_face:

**Comment by Nashtare** [comment]
> we are very interested in the relative merits of Poseidon vs Tip5!

You may be interested in [https://toposware.com/paper_tip5.pdf](https://toposware.com/paper_tip5.pdf), adapting Tip5 to 128-bit security (originally targetting 160), with a focus on performances. The second instance (size 12 like the current Poseidon implem), is very close to SHA3, when implemented on the winterfell backend (unfortunately Winterfell doesn't implement Poseidon). I don't have estimates on how good of a speed-up we'd get by benefiting from plonky2 assembly instructions (both at the field level and hash level), but this should be really performant.

**Comment by jan-ferdinand** [comment]
Here are my findings. They are acquired by running `cargo bench -- hash_10` on [this branch](https://github.com/Neptune-Crypto/twenty-first/tree/poseidon_bench).

| Hash Function        | Time [μs] |
|:---------------------|:----------|
| Rescue Prime Regular   | 17.298    |
| Rescue Prime Optimized | 11.907    |
| Poseidon             | &nbsp;&nbsp;6.253   |
| Tip5                 | &nbsp;&nbsp;1.037   |

Note that we're not yet done optimizing Tip5 – @aszepieniec has an even faster implementation in the works.

**Comment by Nashtare** [comment]
I am not sure the comparison is accurate. The current instantiation of Poseidon in this repository, originally targeting 100 bits of security, is actually reaching rather ~95 bits of security when considering  [ https://tosc.iacr.org/index.php/ToSC/article/view/9850/9350](https://tosc.iacr.org/index.php/ToSC/article/view/9850/9350) (as mentioned in the code).

In your implementation, the number of rounds (RF and RP) will also satisfy around ~95 bits, considering this attack, instead of 160 bits, for proper comparison with your instantiations of RPO and Tip5. (This actually plays _in favor_ of Tip5 or [variants at 128 bits of security](https://toposware.com/paper_tip5.pdf) we described, as Poseidon instantiations at these security levels would actually be slower).

**Comment by jan-ferdinand** [comment]
Thanks for checking out the code! (I'm assuming that's what you did. :slightly_smiling_face:)

I derived the number of rounds using the scripts provided by the Poseidon authors and re-ran the computation with the recently published `mir-protocol/hash-constants` repository. They both agreed and I hence assumed the parameters to be fine. Thanks for pointing out that apparently, that was incorrect.

Do you happen to have a way for deriving round constants that factors in the linked attack at hand?
